name = "oldmontrealmap"
account_id = "3da170f83992089a9eebdd5bee516d04"
compatibility_date = "2025-01-01"
main = "src/index.js"

[assets]
directory = "."

[[routes]]
pattern = "oldmontrealmap.ca/*"
zone_name = "oldmontrealmap.ca"

[[routes]]
pattern = "www.oldmontrealmap.ca/*"
zone_name = "oldmontrealmap.ca"

[[routes]]
pattern = "cartevieuxmontreal.ca/*"
zone_name = "cartevieuxmontreal.ca"

[[routes]]
pattern = "www.cartevieuxmontreal.ca/*"
zone_name = "cartevieuxmontreal.ca"

[[env.production.bindings]]
binding = "ASSETS"
type = "service"
service = "oldmontrealmap"