name = "oldmontrealmap"
compatibility_date = "2025-01-01"
main = "worker/index.js"

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "404-page"

[[routes]]
pattern = "oldmontrealmap.ca/*"
zone_name = "oldmontrealmap.ca"

[[routes]]
pattern = "www.oldmontrealmap.ca/*"
zone_name = "oldmontrealmap.ca"

[[routes]]
pattern = "cartevieuxmontreal.ca/*"
zone_name = "cartevieuxmontreal.ca"

[[routes]]
pattern = "www.cartevieuxmontreal.ca/*"
zone_name = "cartevieuxmontreal.ca"